package com.esofthead.mycollab.module.tracker.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public HistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return (Criteria) this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return (Criteria) this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andAssignuserIsNull() {
            addCriterion("assignuser is null");
            return (Criteria) this;
        }

        public Criteria andAssignuserIsNotNull() {
            addCriterion("assignuser is not null");
            return (Criteria) this;
        }

        public Criteria andAssignuserEqualTo(String value) {
            addCriterion("assignuser =", value, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserNotEqualTo(String value) {
            addCriterion("assignuser <>", value, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserGreaterThan(String value) {
            addCriterion("assignuser >", value, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserGreaterThanOrEqualTo(String value) {
            addCriterion("assignuser >=", value, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserLessThan(String value) {
            addCriterion("assignuser <", value, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserLessThanOrEqualTo(String value) {
            addCriterion("assignuser <=", value, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserLike(String value) {
            addCriterion("assignuser like", value, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserNotLike(String value) {
            addCriterion("assignuser not like", value, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserIn(List<String> values) {
            addCriterion("assignuser in", values, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserNotIn(List<String> values) {
            addCriterion("assignuser not in", values, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserBetween(String value1, String value2) {
            addCriterion("assignuser between", value1, value2, "assignuser");
            return (Criteria) this;
        }

        public Criteria andAssignuserNotBetween(String value1, String value2) {
            addCriterion("assignuser not between", value1, value2, "assignuser");
            return (Criteria) this;
        }

        public Criteria andPosteddateIsNull() {
            addCriterion("posteddate is null");
            return (Criteria) this;
        }

        public Criteria andPosteddateIsNotNull() {
            addCriterion("posteddate is not null");
            return (Criteria) this;
        }

        public Criteria andPosteddateEqualTo(Date value) {
            addCriterion("posteddate =", value, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateNotEqualTo(Date value) {
            addCriterion("posteddate <>", value, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateGreaterThan(Date value) {
            addCriterion("posteddate >", value, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateGreaterThanOrEqualTo(Date value) {
            addCriterion("posteddate >=", value, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateLessThan(Date value) {
            addCriterion("posteddate <", value, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateLessThanOrEqualTo(Date value) {
            addCriterion("posteddate <=", value, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateIn(List<Date> values) {
            addCriterion("posteddate in", values, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateNotIn(List<Date> values) {
            addCriterion("posteddate not in", values, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateBetween(Date value1, Date value2) {
            addCriterion("posteddate between", value1, value2, "posteddate");
            return (Criteria) this;
        }

        public Criteria andPosteddateNotBetween(Date value1, Date value2) {
            addCriterion("posteddate not between", value1, value2, "posteddate");
            return (Criteria) this;
        }

        public Criteria andLogbyIsNull() {
            addCriterion("logby is null");
            return (Criteria) this;
        }

        public Criteria andLogbyIsNotNull() {
            addCriterion("logby is not null");
            return (Criteria) this;
        }

        public Criteria andLogbyEqualTo(String value) {
            addCriterion("logby =", value, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyNotEqualTo(String value) {
            addCriterion("logby <>", value, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyGreaterThan(String value) {
            addCriterion("logby >", value, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyGreaterThanOrEqualTo(String value) {
            addCriterion("logby >=", value, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyLessThan(String value) {
            addCriterion("logby <", value, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyLessThanOrEqualTo(String value) {
            addCriterion("logby <=", value, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyLike(String value) {
            addCriterion("logby like", value, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyNotLike(String value) {
            addCriterion("logby not like", value, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyIn(List<String> values) {
            addCriterion("logby in", values, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyNotIn(List<String> values) {
            addCriterion("logby not in", values, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyBetween(String value1, String value2) {
            addCriterion("logby between", value1, value2, "logby");
            return (Criteria) this;
        }

        public Criteria andLogbyNotBetween(String value1, String value2) {
            addCriterion("logby not between", value1, value2, "logby");
            return (Criteria) this;
        }

        public Criteria andSeverityIsNull() {
            addCriterion("severity is null");
            return (Criteria) this;
        }

        public Criteria andSeverityIsNotNull() {
            addCriterion("severity is not null");
            return (Criteria) this;
        }

        public Criteria andSeverityEqualTo(Integer value) {
            addCriterion("severity =", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityNotEqualTo(Integer value) {
            addCriterion("severity <>", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityGreaterThan(Integer value) {
            addCriterion("severity >", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityGreaterThanOrEqualTo(Integer value) {
            addCriterion("severity >=", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityLessThan(Integer value) {
            addCriterion("severity <", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityLessThanOrEqualTo(Integer value) {
            addCriterion("severity <=", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityIn(List<Integer> values) {
            addCriterion("severity in", values, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityNotIn(List<Integer> values) {
            addCriterion("severity not in", values, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityBetween(Integer value1, Integer value2) {
            addCriterion("severity between", value1, value2, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityNotBetween(Integer value1, Integer value2) {
            addCriterion("severity not between", value1, value2, "severity");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIsNull() {
            addCriterion("environment is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIsNotNull() {
            addCriterion("environment is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentEqualTo(String value) {
            addCriterion("environment =", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotEqualTo(String value) {
            addCriterion("environment <>", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentGreaterThan(String value) {
            addCriterion("environment >", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentGreaterThanOrEqualTo(String value) {
            addCriterion("environment >=", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLessThan(String value) {
            addCriterion("environment <", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLessThanOrEqualTo(String value) {
            addCriterion("environment <=", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLike(String value) {
            addCriterion("environment like", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotLike(String value) {
            addCriterion("environment not like", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIn(List<String> values) {
            addCriterion("environment in", values, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotIn(List<String> values) {
            addCriterion("environment not in", values, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentBetween(String value1, String value2) {
            addCriterion("environment between", value1, value2, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotBetween(String value1, String value2) {
            addCriterion("environment not between", value1, value2, "environment");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsIsNull() {
            addCriterion("affectedversions is null");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsIsNotNull() {
            addCriterion("affectedversions is not null");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsEqualTo(String value) {
            addCriterion("affectedversions =", value, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsNotEqualTo(String value) {
            addCriterion("affectedversions <>", value, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsGreaterThan(String value) {
            addCriterion("affectedversions >", value, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsGreaterThanOrEqualTo(String value) {
            addCriterion("affectedversions >=", value, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsLessThan(String value) {
            addCriterion("affectedversions <", value, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsLessThanOrEqualTo(String value) {
            addCriterion("affectedversions <=", value, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsLike(String value) {
            addCriterion("affectedversions like", value, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsNotLike(String value) {
            addCriterion("affectedversions not like", value, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsIn(List<String> values) {
            addCriterion("affectedversions in", values, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsNotIn(List<String> values) {
            addCriterion("affectedversions not in", values, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsBetween(String value1, String value2) {
            addCriterion("affectedversions between", value1, value2, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andAffectedversionsNotBetween(String value1, String value2) {
            addCriterion("affectedversions not between", value1, value2, "affectedversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsIsNull() {
            addCriterion("fixonversions is null");
            return (Criteria) this;
        }

        public Criteria andFixonversionsIsNotNull() {
            addCriterion("fixonversions is not null");
            return (Criteria) this;
        }

        public Criteria andFixonversionsEqualTo(String value) {
            addCriterion("fixonversions =", value, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsNotEqualTo(String value) {
            addCriterion("fixonversions <>", value, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsGreaterThan(String value) {
            addCriterion("fixonversions >", value, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsGreaterThanOrEqualTo(String value) {
            addCriterion("fixonversions >=", value, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsLessThan(String value) {
            addCriterion("fixonversions <", value, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsLessThanOrEqualTo(String value) {
            addCriterion("fixonversions <=", value, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsLike(String value) {
            addCriterion("fixonversions like", value, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsNotLike(String value) {
            addCriterion("fixonversions not like", value, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsIn(List<String> values) {
            addCriterion("fixonversions in", values, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsNotIn(List<String> values) {
            addCriterion("fixonversions not in", values, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsBetween(String value1, String value2) {
            addCriterion("fixonversions between", value1, value2, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andFixonversionsNotBetween(String value1, String value2) {
            addCriterion("fixonversions not between", value1, value2, "fixonversions");
            return (Criteria) this;
        }

        public Criteria andResolutionIsNull() {
            addCriterion("resolution is null");
            return (Criteria) this;
        }

        public Criteria andResolutionIsNotNull() {
            addCriterion("resolution is not null");
            return (Criteria) this;
        }

        public Criteria andResolutionEqualTo(Integer value) {
            addCriterion("resolution =", value, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionNotEqualTo(Integer value) {
            addCriterion("resolution <>", value, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionGreaterThan(Integer value) {
            addCriterion("resolution >", value, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionGreaterThanOrEqualTo(Integer value) {
            addCriterion("resolution >=", value, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionLessThan(Integer value) {
            addCriterion("resolution <", value, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionLessThanOrEqualTo(Integer value) {
            addCriterion("resolution <=", value, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionIn(List<Integer> values) {
            addCriterion("resolution in", values, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionNotIn(List<Integer> values) {
            addCriterion("resolution not in", values, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionBetween(Integer value1, Integer value2) {
            addCriterion("resolution between", value1, value2, "resolution");
            return (Criteria) this;
        }

        public Criteria andResolutionNotBetween(Integer value1, Integer value2) {
            addCriterion("resolution not between", value1, value2, "resolution");
            return (Criteria) this;
        }

        public Criteria andRelatedbugIsNull() {
            addCriterion("relatedbug is null");
            return (Criteria) this;
        }

        public Criteria andRelatedbugIsNotNull() {
            addCriterion("relatedbug is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedbugEqualTo(Integer value) {
            addCriterion("relatedbug =", value, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugNotEqualTo(Integer value) {
            addCriterion("relatedbug <>", value, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugGreaterThan(Integer value) {
            addCriterion("relatedbug >", value, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugGreaterThanOrEqualTo(Integer value) {
            addCriterion("relatedbug >=", value, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugLessThan(Integer value) {
            addCriterion("relatedbug <", value, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugLessThanOrEqualTo(Integer value) {
            addCriterion("relatedbug <=", value, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugIn(List<Integer> values) {
            addCriterion("relatedbug in", values, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugNotIn(List<Integer> values) {
            addCriterion("relatedbug not in", values, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugBetween(Integer value1, Integer value2) {
            addCriterion("relatedbug between", value1, value2, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andRelatedbugNotBetween(Integer value1, Integer value2) {
            addCriterion("relatedbug not between", value1, value2, "relatedbug");
            return (Criteria) this;
        }

        public Criteria andCusInt01IsNull() {
            addCriterion("cus_int_01 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt01IsNotNull() {
            addCriterion("cus_int_01 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt01EqualTo(Integer value) {
            addCriterion("cus_int_01 =", value, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01NotEqualTo(Integer value) {
            addCriterion("cus_int_01 <>", value, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01GreaterThan(Integer value) {
            addCriterion("cus_int_01 >", value, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_01 >=", value, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01LessThan(Integer value) {
            addCriterion("cus_int_01 <", value, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_01 <=", value, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01In(List<Integer> values) {
            addCriterion("cus_int_01 in", values, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01NotIn(List<Integer> values) {
            addCriterion("cus_int_01 not in", values, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01Between(Integer value1, Integer value2) {
            addCriterion("cus_int_01 between", value1, value2, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt01NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_01 not between", value1, value2, "cusInt01");
            return (Criteria) this;
        }

        public Criteria andCusInt02IsNull() {
            addCriterion("cus_int_02 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt02IsNotNull() {
            addCriterion("cus_int_02 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt02EqualTo(Integer value) {
            addCriterion("cus_int_02 =", value, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02NotEqualTo(Integer value) {
            addCriterion("cus_int_02 <>", value, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02GreaterThan(Integer value) {
            addCriterion("cus_int_02 >", value, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_02 >=", value, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02LessThan(Integer value) {
            addCriterion("cus_int_02 <", value, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_02 <=", value, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02In(List<Integer> values) {
            addCriterion("cus_int_02 in", values, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02NotIn(List<Integer> values) {
            addCriterion("cus_int_02 not in", values, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02Between(Integer value1, Integer value2) {
            addCriterion("cus_int_02 between", value1, value2, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt02NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_02 not between", value1, value2, "cusInt02");
            return (Criteria) this;
        }

        public Criteria andCusInt03IsNull() {
            addCriterion("cus_int_03 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt03IsNotNull() {
            addCriterion("cus_int_03 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt03EqualTo(Integer value) {
            addCriterion("cus_int_03 =", value, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03NotEqualTo(Integer value) {
            addCriterion("cus_int_03 <>", value, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03GreaterThan(Integer value) {
            addCriterion("cus_int_03 >", value, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_03 >=", value, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03LessThan(Integer value) {
            addCriterion("cus_int_03 <", value, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_03 <=", value, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03In(List<Integer> values) {
            addCriterion("cus_int_03 in", values, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03NotIn(List<Integer> values) {
            addCriterion("cus_int_03 not in", values, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03Between(Integer value1, Integer value2) {
            addCriterion("cus_int_03 between", value1, value2, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt03NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_03 not between", value1, value2, "cusInt03");
            return (Criteria) this;
        }

        public Criteria andCusInt04IsNull() {
            addCriterion("cus_int_04 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt04IsNotNull() {
            addCriterion("cus_int_04 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt04EqualTo(Integer value) {
            addCriterion("cus_int_04 =", value, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04NotEqualTo(Integer value) {
            addCriterion("cus_int_04 <>", value, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04GreaterThan(Integer value) {
            addCriterion("cus_int_04 >", value, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_04 >=", value, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04LessThan(Integer value) {
            addCriterion("cus_int_04 <", value, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_04 <=", value, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04In(List<Integer> values) {
            addCriterion("cus_int_04 in", values, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04NotIn(List<Integer> values) {
            addCriterion("cus_int_04 not in", values, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04Between(Integer value1, Integer value2) {
            addCriterion("cus_int_04 between", value1, value2, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt04NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_04 not between", value1, value2, "cusInt04");
            return (Criteria) this;
        }

        public Criteria andCusInt05IsNull() {
            addCriterion("cus_int_05 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt05IsNotNull() {
            addCriterion("cus_int_05 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt05EqualTo(Integer value) {
            addCriterion("cus_int_05 =", value, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05NotEqualTo(Integer value) {
            addCriterion("cus_int_05 <>", value, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05GreaterThan(Integer value) {
            addCriterion("cus_int_05 >", value, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_05 >=", value, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05LessThan(Integer value) {
            addCriterion("cus_int_05 <", value, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_05 <=", value, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05In(List<Integer> values) {
            addCriterion("cus_int_05 in", values, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05NotIn(List<Integer> values) {
            addCriterion("cus_int_05 not in", values, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05Between(Integer value1, Integer value2) {
            addCriterion("cus_int_05 between", value1, value2, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt05NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_05 not between", value1, value2, "cusInt05");
            return (Criteria) this;
        }

        public Criteria andCusInt06IsNull() {
            addCriterion("cus_int_06 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt06IsNotNull() {
            addCriterion("cus_int_06 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt06EqualTo(Integer value) {
            addCriterion("cus_int_06 =", value, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06NotEqualTo(Integer value) {
            addCriterion("cus_int_06 <>", value, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06GreaterThan(Integer value) {
            addCriterion("cus_int_06 >", value, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_06 >=", value, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06LessThan(Integer value) {
            addCriterion("cus_int_06 <", value, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_06 <=", value, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06In(List<Integer> values) {
            addCriterion("cus_int_06 in", values, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06NotIn(List<Integer> values) {
            addCriterion("cus_int_06 not in", values, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06Between(Integer value1, Integer value2) {
            addCriterion("cus_int_06 between", value1, value2, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt06NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_06 not between", value1, value2, "cusInt06");
            return (Criteria) this;
        }

        public Criteria andCusInt07IsNull() {
            addCriterion("cus_int_07 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt07IsNotNull() {
            addCriterion("cus_int_07 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt07EqualTo(Integer value) {
            addCriterion("cus_int_07 =", value, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07NotEqualTo(Integer value) {
            addCriterion("cus_int_07 <>", value, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07GreaterThan(Integer value) {
            addCriterion("cus_int_07 >", value, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_07 >=", value, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07LessThan(Integer value) {
            addCriterion("cus_int_07 <", value, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_07 <=", value, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07In(List<Integer> values) {
            addCriterion("cus_int_07 in", values, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07NotIn(List<Integer> values) {
            addCriterion("cus_int_07 not in", values, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07Between(Integer value1, Integer value2) {
            addCriterion("cus_int_07 between", value1, value2, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt07NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_07 not between", value1, value2, "cusInt07");
            return (Criteria) this;
        }

        public Criteria andCusInt08IsNull() {
            addCriterion("cus_int_08 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt08IsNotNull() {
            addCriterion("cus_int_08 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt08EqualTo(Integer value) {
            addCriterion("cus_int_08 =", value, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08NotEqualTo(Integer value) {
            addCriterion("cus_int_08 <>", value, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08GreaterThan(Integer value) {
            addCriterion("cus_int_08 >", value, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_08 >=", value, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08LessThan(Integer value) {
            addCriterion("cus_int_08 <", value, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_08 <=", value, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08In(List<Integer> values) {
            addCriterion("cus_int_08 in", values, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08NotIn(List<Integer> values) {
            addCriterion("cus_int_08 not in", values, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08Between(Integer value1, Integer value2) {
            addCriterion("cus_int_08 between", value1, value2, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt08NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_08 not between", value1, value2, "cusInt08");
            return (Criteria) this;
        }

        public Criteria andCusInt09IsNull() {
            addCriterion("cus_int_09 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt09IsNotNull() {
            addCriterion("cus_int_09 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt09EqualTo(Integer value) {
            addCriterion("cus_int_09 =", value, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09NotEqualTo(Integer value) {
            addCriterion("cus_int_09 <>", value, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09GreaterThan(Integer value) {
            addCriterion("cus_int_09 >", value, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_09 >=", value, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09LessThan(Integer value) {
            addCriterion("cus_int_09 <", value, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_09 <=", value, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09In(List<Integer> values) {
            addCriterion("cus_int_09 in", values, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09NotIn(List<Integer> values) {
            addCriterion("cus_int_09 not in", values, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09Between(Integer value1, Integer value2) {
            addCriterion("cus_int_09 between", value1, value2, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt09NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_09 not between", value1, value2, "cusInt09");
            return (Criteria) this;
        }

        public Criteria andCusInt10IsNull() {
            addCriterion("cus_int_10 is null");
            return (Criteria) this;
        }

        public Criteria andCusInt10IsNotNull() {
            addCriterion("cus_int_10 is not null");
            return (Criteria) this;
        }

        public Criteria andCusInt10EqualTo(Integer value) {
            addCriterion("cus_int_10 =", value, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10NotEqualTo(Integer value) {
            addCriterion("cus_int_10 <>", value, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10GreaterThan(Integer value) {
            addCriterion("cus_int_10 >", value, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10GreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_int_10 >=", value, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10LessThan(Integer value) {
            addCriterion("cus_int_10 <", value, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10LessThanOrEqualTo(Integer value) {
            addCriterion("cus_int_10 <=", value, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10In(List<Integer> values) {
            addCriterion("cus_int_10 in", values, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10NotIn(List<Integer> values) {
            addCriterion("cus_int_10 not in", values, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10Between(Integer value1, Integer value2) {
            addCriterion("cus_int_10 between", value1, value2, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusInt10NotBetween(Integer value1, Integer value2) {
            addCriterion("cus_int_10 not between", value1, value2, "cusInt10");
            return (Criteria) this;
        }

        public Criteria andCusStr01IsNull() {
            addCriterion("cus_str_01 is null");
            return (Criteria) this;
        }

        public Criteria andCusStr01IsNotNull() {
            addCriterion("cus_str_01 is not null");
            return (Criteria) this;
        }

        public Criteria andCusStr01EqualTo(String value) {
            addCriterion("cus_str_01 =", value, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01NotEqualTo(String value) {
            addCriterion("cus_str_01 <>", value, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01GreaterThan(String value) {
            addCriterion("cus_str_01 >", value, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01GreaterThanOrEqualTo(String value) {
            addCriterion("cus_str_01 >=", value, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01LessThan(String value) {
            addCriterion("cus_str_01 <", value, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01LessThanOrEqualTo(String value) {
            addCriterion("cus_str_01 <=", value, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01Like(String value) {
            addCriterion("cus_str_01 like", value, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01NotLike(String value) {
            addCriterion("cus_str_01 not like", value, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01In(List<String> values) {
            addCriterion("cus_str_01 in", values, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01NotIn(List<String> values) {
            addCriterion("cus_str_01 not in", values, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01Between(String value1, String value2) {
            addCriterion("cus_str_01 between", value1, value2, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr01NotBetween(String value1, String value2) {
            addCriterion("cus_str_01 not between", value1, value2, "cusStr01");
            return (Criteria) this;
        }

        public Criteria andCusStr02IsNull() {
            addCriterion("cus_str_02 is null");
            return (Criteria) this;
        }

        public Criteria andCusStr02IsNotNull() {
            addCriterion("cus_str_02 is not null");
            return (Criteria) this;
        }

        public Criteria andCusStr02EqualTo(String value) {
            addCriterion("cus_str_02 =", value, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02NotEqualTo(String value) {
            addCriterion("cus_str_02 <>", value, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02GreaterThan(String value) {
            addCriterion("cus_str_02 >", value, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02GreaterThanOrEqualTo(String value) {
            addCriterion("cus_str_02 >=", value, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02LessThan(String value) {
            addCriterion("cus_str_02 <", value, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02LessThanOrEqualTo(String value) {
            addCriterion("cus_str_02 <=", value, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02Like(String value) {
            addCriterion("cus_str_02 like", value, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02NotLike(String value) {
            addCriterion("cus_str_02 not like", value, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02In(List<String> values) {
            addCriterion("cus_str_02 in", values, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02NotIn(List<String> values) {
            addCriterion("cus_str_02 not in", values, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02Between(String value1, String value2) {
            addCriterion("cus_str_02 between", value1, value2, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr02NotBetween(String value1, String value2) {
            addCriterion("cus_str_02 not between", value1, value2, "cusStr02");
            return (Criteria) this;
        }

        public Criteria andCusStr03IsNull() {
            addCriterion("cus_str_03 is null");
            return (Criteria) this;
        }

        public Criteria andCusStr03IsNotNull() {
            addCriterion("cus_str_03 is not null");
            return (Criteria) this;
        }

        public Criteria andCusStr03EqualTo(String value) {
            addCriterion("cus_str_03 =", value, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03NotEqualTo(String value) {
            addCriterion("cus_str_03 <>", value, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03GreaterThan(String value) {
            addCriterion("cus_str_03 >", value, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03GreaterThanOrEqualTo(String value) {
            addCriterion("cus_str_03 >=", value, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03LessThan(String value) {
            addCriterion("cus_str_03 <", value, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03LessThanOrEqualTo(String value) {
            addCriterion("cus_str_03 <=", value, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03Like(String value) {
            addCriterion("cus_str_03 like", value, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03NotLike(String value) {
            addCriterion("cus_str_03 not like", value, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03In(List<String> values) {
            addCriterion("cus_str_03 in", values, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03NotIn(List<String> values) {
            addCriterion("cus_str_03 not in", values, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03Between(String value1, String value2) {
            addCriterion("cus_str_03 between", value1, value2, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr03NotBetween(String value1, String value2) {
            addCriterion("cus_str_03 not between", value1, value2, "cusStr03");
            return (Criteria) this;
        }

        public Criteria andCusStr04IsNull() {
            addCriterion("cus_str_04 is null");
            return (Criteria) this;
        }

        public Criteria andCusStr04IsNotNull() {
            addCriterion("cus_str_04 is not null");
            return (Criteria) this;
        }

        public Criteria andCusStr04EqualTo(String value) {
            addCriterion("cus_str_04 =", value, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04NotEqualTo(String value) {
            addCriterion("cus_str_04 <>", value, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04GreaterThan(String value) {
            addCriterion("cus_str_04 >", value, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04GreaterThanOrEqualTo(String value) {
            addCriterion("cus_str_04 >=", value, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04LessThan(String value) {
            addCriterion("cus_str_04 <", value, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04LessThanOrEqualTo(String value) {
            addCriterion("cus_str_04 <=", value, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04Like(String value) {
            addCriterion("cus_str_04 like", value, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04NotLike(String value) {
            addCriterion("cus_str_04 not like", value, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04In(List<String> values) {
            addCriterion("cus_str_04 in", values, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04NotIn(List<String> values) {
            addCriterion("cus_str_04 not in", values, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04Between(String value1, String value2) {
            addCriterion("cus_str_04 between", value1, value2, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr04NotBetween(String value1, String value2) {
            addCriterion("cus_str_04 not between", value1, value2, "cusStr04");
            return (Criteria) this;
        }

        public Criteria andCusStr05IsNull() {
            addCriterion("cus_str_05 is null");
            return (Criteria) this;
        }

        public Criteria andCusStr05IsNotNull() {
            addCriterion("cus_str_05 is not null");
            return (Criteria) this;
        }

        public Criteria andCusStr05EqualTo(String value) {
            addCriterion("cus_str_05 =", value, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05NotEqualTo(String value) {
            addCriterion("cus_str_05 <>", value, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05GreaterThan(String value) {
            addCriterion("cus_str_05 >", value, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05GreaterThanOrEqualTo(String value) {
            addCriterion("cus_str_05 >=", value, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05LessThan(String value) {
            addCriterion("cus_str_05 <", value, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05LessThanOrEqualTo(String value) {
            addCriterion("cus_str_05 <=", value, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05Like(String value) {
            addCriterion("cus_str_05 like", value, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05NotLike(String value) {
            addCriterion("cus_str_05 not like", value, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05In(List<String> values) {
            addCriterion("cus_str_05 in", values, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05NotIn(List<String> values) {
            addCriterion("cus_str_05 not in", values, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05Between(String value1, String value2) {
            addCriterion("cus_str_05 between", value1, value2, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusStr05NotBetween(String value1, String value2) {
            addCriterion("cus_str_05 not between", value1, value2, "cusStr05");
            return (Criteria) this;
        }

        public Criteria andCusTime01IsNull() {
            addCriterion("cus_time_01 is null");
            return (Criteria) this;
        }

        public Criteria andCusTime01IsNotNull() {
            addCriterion("cus_time_01 is not null");
            return (Criteria) this;
        }

        public Criteria andCusTime01EqualTo(Date value) {
            addCriterion("cus_time_01 =", value, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01NotEqualTo(Date value) {
            addCriterion("cus_time_01 <>", value, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01GreaterThan(Date value) {
            addCriterion("cus_time_01 >", value, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01GreaterThanOrEqualTo(Date value) {
            addCriterion("cus_time_01 >=", value, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01LessThan(Date value) {
            addCriterion("cus_time_01 <", value, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01LessThanOrEqualTo(Date value) {
            addCriterion("cus_time_01 <=", value, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01In(List<Date> values) {
            addCriterion("cus_time_01 in", values, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01NotIn(List<Date> values) {
            addCriterion("cus_time_01 not in", values, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01Between(Date value1, Date value2) {
            addCriterion("cus_time_01 between", value1, value2, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime01NotBetween(Date value1, Date value2) {
            addCriterion("cus_time_01 not between", value1, value2, "cusTime01");
            return (Criteria) this;
        }

        public Criteria andCusTime02IsNull() {
            addCriterion("cus_time_02 is null");
            return (Criteria) this;
        }

        public Criteria andCusTime02IsNotNull() {
            addCriterion("cus_time_02 is not null");
            return (Criteria) this;
        }

        public Criteria andCusTime02EqualTo(Date value) {
            addCriterion("cus_time_02 =", value, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02NotEqualTo(Date value) {
            addCriterion("cus_time_02 <>", value, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02GreaterThan(Date value) {
            addCriterion("cus_time_02 >", value, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02GreaterThanOrEqualTo(Date value) {
            addCriterion("cus_time_02 >=", value, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02LessThan(Date value) {
            addCriterion("cus_time_02 <", value, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02LessThanOrEqualTo(Date value) {
            addCriterion("cus_time_02 <=", value, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02In(List<Date> values) {
            addCriterion("cus_time_02 in", values, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02NotIn(List<Date> values) {
            addCriterion("cus_time_02 not in", values, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02Between(Date value1, Date value2) {
            addCriterion("cus_time_02 between", value1, value2, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime02NotBetween(Date value1, Date value2) {
            addCriterion("cus_time_02 not between", value1, value2, "cusTime02");
            return (Criteria) this;
        }

        public Criteria andCusTime03IsNull() {
            addCriterion("cus_time_03 is null");
            return (Criteria) this;
        }

        public Criteria andCusTime03IsNotNull() {
            addCriterion("cus_time_03 is not null");
            return (Criteria) this;
        }

        public Criteria andCusTime03EqualTo(Date value) {
            addCriterion("cus_time_03 =", value, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03NotEqualTo(Date value) {
            addCriterion("cus_time_03 <>", value, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03GreaterThan(Date value) {
            addCriterion("cus_time_03 >", value, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03GreaterThanOrEqualTo(Date value) {
            addCriterion("cus_time_03 >=", value, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03LessThan(Date value) {
            addCriterion("cus_time_03 <", value, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03LessThanOrEqualTo(Date value) {
            addCriterion("cus_time_03 <=", value, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03In(List<Date> values) {
            addCriterion("cus_time_03 in", values, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03NotIn(List<Date> values) {
            addCriterion("cus_time_03 not in", values, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03Between(Date value1, Date value2) {
            addCriterion("cus_time_03 between", value1, value2, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime03NotBetween(Date value1, Date value2) {
            addCriterion("cus_time_03 not between", value1, value2, "cusTime03");
            return (Criteria) this;
        }

        public Criteria andCusTime04IsNull() {
            addCriterion("cus_time_04 is null");
            return (Criteria) this;
        }

        public Criteria andCusTime04IsNotNull() {
            addCriterion("cus_time_04 is not null");
            return (Criteria) this;
        }

        public Criteria andCusTime04EqualTo(Date value) {
            addCriterion("cus_time_04 =", value, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04NotEqualTo(Date value) {
            addCriterion("cus_time_04 <>", value, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04GreaterThan(Date value) {
            addCriterion("cus_time_04 >", value, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04GreaterThanOrEqualTo(Date value) {
            addCriterion("cus_time_04 >=", value, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04LessThan(Date value) {
            addCriterion("cus_time_04 <", value, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04LessThanOrEqualTo(Date value) {
            addCriterion("cus_time_04 <=", value, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04In(List<Date> values) {
            addCriterion("cus_time_04 in", values, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04NotIn(List<Date> values) {
            addCriterion("cus_time_04 not in", values, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04Between(Date value1, Date value2) {
            addCriterion("cus_time_04 between", value1, value2, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusTime04NotBetween(Date value1, Date value2) {
            addCriterion("cus_time_04 not between", value1, value2, "cusTime04");
            return (Criteria) this;
        }

        public Criteria andCusDbl01IsNull() {
            addCriterion("cus_dbl_01 is null");
            return (Criteria) this;
        }

        public Criteria andCusDbl01IsNotNull() {
            addCriterion("cus_dbl_01 is not null");
            return (Criteria) this;
        }

        public Criteria andCusDbl01EqualTo(Double value) {
            addCriterion("cus_dbl_01 =", value, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01NotEqualTo(Double value) {
            addCriterion("cus_dbl_01 <>", value, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01GreaterThan(Double value) {
            addCriterion("cus_dbl_01 >", value, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01GreaterThanOrEqualTo(Double value) {
            addCriterion("cus_dbl_01 >=", value, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01LessThan(Double value) {
            addCriterion("cus_dbl_01 <", value, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01LessThanOrEqualTo(Double value) {
            addCriterion("cus_dbl_01 <=", value, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01In(List<Double> values) {
            addCriterion("cus_dbl_01 in", values, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01NotIn(List<Double> values) {
            addCriterion("cus_dbl_01 not in", values, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01Between(Double value1, Double value2) {
            addCriterion("cus_dbl_01 between", value1, value2, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl01NotBetween(Double value1, Double value2) {
            addCriterion("cus_dbl_01 not between", value1, value2, "cusDbl01");
            return (Criteria) this;
        }

        public Criteria andCusDbl02IsNull() {
            addCriterion("cus_dbl_02 is null");
            return (Criteria) this;
        }

        public Criteria andCusDbl02IsNotNull() {
            addCriterion("cus_dbl_02 is not null");
            return (Criteria) this;
        }

        public Criteria andCusDbl02EqualTo(Double value) {
            addCriterion("cus_dbl_02 =", value, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02NotEqualTo(Double value) {
            addCriterion("cus_dbl_02 <>", value, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02GreaterThan(Double value) {
            addCriterion("cus_dbl_02 >", value, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02GreaterThanOrEqualTo(Double value) {
            addCriterion("cus_dbl_02 >=", value, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02LessThan(Double value) {
            addCriterion("cus_dbl_02 <", value, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02LessThanOrEqualTo(Double value) {
            addCriterion("cus_dbl_02 <=", value, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02In(List<Double> values) {
            addCriterion("cus_dbl_02 in", values, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02NotIn(List<Double> values) {
            addCriterion("cus_dbl_02 not in", values, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02Between(Double value1, Double value2) {
            addCriterion("cus_dbl_02 between", value1, value2, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl02NotBetween(Double value1, Double value2) {
            addCriterion("cus_dbl_02 not between", value1, value2, "cusDbl02");
            return (Criteria) this;
        }

        public Criteria andCusDbl03IsNull() {
            addCriterion("cus_dbl_03 is null");
            return (Criteria) this;
        }

        public Criteria andCusDbl03IsNotNull() {
            addCriterion("cus_dbl_03 is not null");
            return (Criteria) this;
        }

        public Criteria andCusDbl03EqualTo(Double value) {
            addCriterion("cus_dbl_03 =", value, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03NotEqualTo(Double value) {
            addCriterion("cus_dbl_03 <>", value, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03GreaterThan(Double value) {
            addCriterion("cus_dbl_03 >", value, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03GreaterThanOrEqualTo(Double value) {
            addCriterion("cus_dbl_03 >=", value, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03LessThan(Double value) {
            addCriterion("cus_dbl_03 <", value, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03LessThanOrEqualTo(Double value) {
            addCriterion("cus_dbl_03 <=", value, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03In(List<Double> values) {
            addCriterion("cus_dbl_03 in", values, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03NotIn(List<Double> values) {
            addCriterion("cus_dbl_03 not in", values, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03Between(Double value1, Double value2) {
            addCriterion("cus_dbl_03 between", value1, value2, "cusDbl03");
            return (Criteria) this;
        }

        public Criteria andCusDbl03NotBetween(Double value1, Double value2) {
            addCriterion("cus_dbl_03 not between", value1, value2, "cusDbl03");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_tracker_history
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_tracker_history
     *
     * @mbggenerated Thu Nov 08 02:34:48 GMT+07:00 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}