app:
  name: MyCollab
  description: The world-class collaboration software

server:
  port: 8080
  address: 127.0.0.1
  url: http://${server.address}:${server.port}/
  cdnUrl: http://${server.url}/assets/
  downloadUrl: http://${server.url}/file/
  apiUrl: https://api.mycollab.com/api/

db:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/mycollab_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useCompression=true&useServerPrepStmts=false&verifyServerCertificate=false&useSSL=false
  username: root
  password: esofthead321

mail:
  #smtphost:
  #port:
  #username:
  #password:
  #isTLS: false
  #isSSL: false
  #notify:
  #errorReport: