package com.esofthead.mycollab.module.user.domain;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.username
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.firstname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.middlename
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String middlename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.lastname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.nickname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.dateofbirth
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private Date dateofbirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.password
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.email
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.website
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.displayname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private String displayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.registeredTime
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private Date registeredtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.active
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private Boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.lastAccessedTime
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private Date lastaccessedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.accountId
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.countryid
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    private Integer countryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.username
     *
     * @return the value of s_user.username
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.username
     *
     * @param username the value for s_user.username
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.firstname
     *
     * @return the value of s_user.firstname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.firstname
     *
     * @param firstname the value for s_user.firstname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.middlename
     *
     * @return the value of s_user.middlename
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getMiddlename() {
        return middlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.middlename
     *
     * @param middlename the value for s_user.middlename
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.lastname
     *
     * @return the value of s_user.lastname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.lastname
     *
     * @param lastname the value for s_user.lastname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.nickname
     *
     * @return the value of s_user.nickname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.nickname
     *
     * @param nickname the value for s_user.nickname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.dateofbirth
     *
     * @return the value of s_user.dateofbirth
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public Date getDateofbirth() {
        return dateofbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.dateofbirth
     *
     * @param dateofbirth the value for s_user.dateofbirth
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.password
     *
     * @return the value of s_user.password
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.password
     *
     * @param password the value for s_user.password
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.email
     *
     * @return the value of s_user.email
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.email
     *
     * @param email the value for s_user.email
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.website
     *
     * @return the value of s_user.website
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.website
     *
     * @param website the value for s_user.website
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.displayname
     *
     * @return the value of s_user.displayname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.displayname
     *
     * @param displayname the value for s_user.displayname
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.registeredTime
     *
     * @return the value of s_user.registeredTime
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public Date getRegisteredtime() {
        return registeredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.registeredTime
     *
     * @param registeredtime the value for s_user.registeredTime
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setRegisteredtime(Date registeredtime) {
        this.registeredtime = registeredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.active
     *
     * @return the value of s_user.active
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.active
     *
     * @param active the value for s_user.active
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.lastAccessedTime
     *
     * @return the value of s_user.lastAccessedTime
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public Date getLastaccessedtime() {
        return lastaccessedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.lastAccessedTime
     *
     * @param lastaccessedtime the value for s_user.lastAccessedTime
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setLastaccessedtime(Date lastaccessedtime) {
        this.lastaccessedtime = lastaccessedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.accountId
     *
     * @return the value of s_user.accountId
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.accountId
     *
     * @param accountid the value for s_user.accountId
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.countryid
     *
     * @return the value of s_user.countryid
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.countryid
     *
     * @param countryid the value for s_user.countryid
     *
     * @mbggenerated Tue Oct 23 10:17:22 GMT+07:00 2012
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }
}