server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://hainguyen@bitbucket.org/hainguyen/mycollab-config-repo.git
          username: hainguyen
          password: DtmLinh80
security:
  user:
    name: root
    password: esofthead321