version: '3.1'
services:
    hlsoft-mysql2:
        image: mysql:5.7.26
        restart: always
        hostname: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mycollab123
            MYSQL_DATABASE: mycollab