version: '3.1'
services:
    hlsoft-app:
        image: mycollab
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://hlsoft-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=hlsoft
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hlsoft-elasticsearch:9300
            - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true -Xmx2g -Xms2g
            - ES_JAVA_OPTS= -Xms750m -Xmx750m
        ports:
            - 8080:8080
    hlsoft-mysql:
        extends:
            file: mysql.yml
            service: hlsoft-mysql