version: '3.1'
services:
  hlsoft-mysql:
    image: mysql:5.7.27
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - $PWD/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mycollab123
      MYSQL_DATABASE: mycollab