app:
  name: MyCollab
  description: The world-class collaboration software
  facebookUrl: https://www.facebook.com/mycollab2
  twitterUrl: https://twitter.com/mycollabdotcom
  googleUrl: https://plus.google.com/u/0/b/112053350736358775306/+Mycollab/about/p/pub
  linkedinUrl: http://www.linkedin.com/company/mycollab

server:
  apiUrl: http://api.mycollab.com/api/
  port: 8080
  storageSystem: file
  siteUrl: http://localhost:8080
  resourceDownloadUrl: http://localhost:8080/file/
  cdnUrl: http://localhost:8080/assets/
  tomcat:
    accesslog.directory: logs
    accesslog.enabled: true
    accesslog.pattern: \"%t %a "%r" %s (%D ms)\"
    accesslog.rotate: true

spring:
  datasource:
    url: jdbc:mysql://localhost/mycollab?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useCompression=true&useServerPrepStmts=false&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mycollab123
    driver-class-name: com.mysql.jdbc.Driver