package com.esofthead.mycollab.usertracking.domain;

public class IpCountry extends IpCountryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapper.country_name
     *
     * @mbggenerated Wed Jan 30 15:51:57 ICT 2013
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapper.country_code
     *
     * @mbggenerated Wed Jan 30 15:51:57 ICT 2013
     */
    private String countryCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapper.country_name
     *
     * @return the value of mapper.country_name
     *
     * @mbggenerated Wed Jan 30 15:51:57 ICT 2013
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapper.country_name
     *
     * @param countryName the value for mapper.country_name
     *
     * @mbggenerated Wed Jan 30 15:51:57 ICT 2013
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapper.country_code
     *
     * @return the value of mapper.country_code
     *
     * @mbggenerated Wed Jan 30 15:51:57 ICT 2013
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapper.country_code
     *
     * @param countryCode the value for mapper.country_code
     *
     * @mbggenerated Wed Jan 30 15:51:57 ICT 2013
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
}