package com.esofthead.mycollab.module.project.domain;

public class TaskResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_prj_task_resource.id
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_prj_task_resource.taskid
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    private Integer taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_prj_task_resource.resourceid
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_prj_task_resource.unit
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    private Integer unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_prj_task_resource.id
     *
     * @return the value of m_prj_task_resource.id
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_prj_task_resource.id
     *
     * @param id the value for m_prj_task_resource.id
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_prj_task_resource.taskid
     *
     * @return the value of m_prj_task_resource.taskid
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_prj_task_resource.taskid
     *
     * @param taskid the value for m_prj_task_resource.taskid
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_prj_task_resource.resourceid
     *
     * @return the value of m_prj_task_resource.resourceid
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_prj_task_resource.resourceid
     *
     * @param resourceid the value for m_prj_task_resource.resourceid
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_prj_task_resource.unit
     *
     * @return the value of m_prj_task_resource.unit
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_prj_task_resource.unit
     *
     * @param unit the value for m_prj_task_resource.unit
     *
     * @mbggenerated Fri Nov 09 17:13:41 GMT+07:00 2012
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }
}