app:
  name: MyCollab Scheduler
  description: The world-class collaboration software

spring:
  datasource:
    url: jdbc:mysql://localhost/mycollab?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useCompression=true&useServerPrepStmts=false&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mycollab123